name: Continuous Integration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write

env:
  NPM_TOKEN: ${{ secrets.NPM_DEPLOYER_TOKEN || secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN }}

jobs:
  run-checks-and-tests:
    name: Run checks and tests
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v3

      - name: 💚 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      # current setup uses npm install, do we care?
      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔎 Lint code
        run: npm run code-style:fix

      - name: 🧪 Test
        run: npm run test:unit
        env:
          NODE_ENV: test

  publish:
    name: Run semantic-version and publish to NPM
    runs-on: ubuntu-latest
    needs: [ run-checks-and-tests ]
    steps:
      - name: run-semantic-version
        run: echo "When everything else is working, run 'CI=true npm run semantic-release'"

  # not enabled in the repo, do we want it turned on?
  # dependabot-auto-merge-pr:
  #   uses: ./.github/workflows/_dependabot-auto-merge-pr.yaml
  #   secrets: inherit
  #   needs: [ run-checks-and-tests ]

  failed-slack-notification:
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/_failed_slack_notification.yaml
    secrets: inherit
    needs: [ run-checks-and-tests, publish ] #dependabot-auto-merge-pr,